services:
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    image: mariadb
    networks:
      - inception
    restart: always
    volumes:
      - ../../data:/var/lib/mysql

  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    image: nginx
    networks:
      - inception
    restart: always
    ports:
      - "443:443"
    volumes:
      - ../../data:/var/www/html

  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    depends_on:
      - mariadb
    image: wordpress
    networks:
      - inception
    restart: always
    volumes:
      - ../../data:/var/www/html

networks:
  inception:
    driver: bridge

