services:
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    image: mariadb
    networks:
      - inception
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
      - mariadb
  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    image: wordpress
    volumes:
      - ./web:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb

networks:
  inception:
    driver: bridge


