CREATE DATABASE IF NOT EXISTS wordpress_db;

CREATE USER IF NOT EXISTS 'wp_user'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON  wordpress_db.* TO 'wp_user'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;